version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'password'
    ports:
      - 1433:1433
    volumes:
      - msql_data:/var/opt/msql

volumes:
  msql_data: