name: Build backend project

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build .NET Core Application
        run: dotnet build
        working-directory: ./backend/Parlor.API

      - name: Test .NET Core Application
        run: dotnet test
        working-directory: ./backend/Parlor.API
